[package]
name = "dag-pb"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
libipld-base = { path = "../base" }
prost = "0.6.1"
thiserror = "1.0.11"

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
libipld-macro = { path = "../macro" }
multihash = "0.10.1"
